# TCL File Generated by Component Editor 12.0sp2
# Tue Nov 20 00:17:48 CST 2012
# DO NOT MODIFY


# 
# CY7C67200_IF "CY7C67200_IF" v1.0
# Peli 2012.11.20.00:17:48
# cy7c67200 hpi controller
# 

# 
# request TCL package from ACDS 12.0
# 
package require -exact qsys 12.0


# 
# module CY7C67200_IF
# 
set_module_property DESCRIPTION "cy7c67200 hpi controller"
set_module_property NAME CY7C67200_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc./DE2_115"
set_module_property AUTHOR Peli
set_module_property DISPLAY_NAME CY7C67200_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL CY7C67200_IF
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file CY7C67200_IF.v VERILOG PATH CY7C67200_IF.v

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL CY7C67200_IF
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file CY7C67200_IF.v VERILOG PATH CY7C67200_IF.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hpi
# 
add_interface hpi avalon end
set_interface_property hpi addressUnits WORDS
set_interface_property hpi associatedClock clock_sink
set_interface_property hpi associatedReset clock_sink_reset
set_interface_property hpi bitsPerSymbol 8
set_interface_property hpi burstOnBurstBoundariesOnly false
set_interface_property hpi burstcountUnits WORDS
set_interface_property hpi explicitAddressSpan 0
set_interface_property hpi holdTime 180
set_interface_property hpi linewrapBursts false
set_interface_property hpi maximumPendingReadTransactions 0
set_interface_property hpi readLatency 0
set_interface_property hpi readWaitStates 180
set_interface_property hpi readWaitTime 180
set_interface_property hpi setupTime 180
set_interface_property hpi timingUnits Nanoseconds
set_interface_property hpi writeWaitStates 180
set_interface_property hpi writeWaitTime 180
set_interface_property hpi ENABLED true

add_interface_port hpi oDATA readdata Output 32
add_interface_port hpi iADDR address Input 2
add_interface_port hpi iRD_N read_n Input 1
add_interface_port hpi iWR_N write_n Input 1
add_interface_port hpi iCS_N chipselect_n Input 1
add_interface_port hpi iDATA writedata Input 32
set_interface_assignment hpi embeddedsw.configuration.isFlash 0
set_interface_assignment hpi embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hpi embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hpi embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink iCLK clk Input 1


# 
# connection point clock_sink_reset
# 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT
set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset iRST_N reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint hpi
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset clock_sink_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender oINT irq Output 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end HPI_DATA export Bidir 16
add_interface_port conduit_end HPI_ADDR export Output 2
add_interface_port conduit_end HPI_RD_N export Output 1
add_interface_port conduit_end HPI_WR_N export Output 1
add_interface_port conduit_end HPI_CS_N export Output 1
add_interface_port conduit_end HPI_RST_N export Output 1
add_interface_port conduit_end HPI_INT export Input 1

